[package]
name = "fast-whisper-burn"
version = "0.1.0"
edition = "2024"

[dependencies]
burn         = { git = "https://github.com/tracel-ai/burn.git",   rev = "ed72d2b", features = ["wgpu", "autotune", "fusion", "ndarray"] }
burn-store   = { git = "https://github.com/tracel-ai/burn.git",   rev = "ed72d2b", features = ["burnpack", "pytorch"] }
burn-cubecl  = { git = "https://github.com/tracel-ai/burn.git",   rev = "ed72d2b" }
burn-fusion  = { git = "https://github.com/tracel-ai/burn.git",   rev = "ed72d2b" }
burn-ir      = { git = "https://github.com/tracel-ai/burn.git",   rev = "ed72d2b" }
burn-backend = { git = "https://github.com/tracel-ai/burn.git",   rev = "ed72d2b" }
cubecl       = { git = "https://github.com/tracel-ai/cubecl.git", rev = "5b831a3cfac3eca0065fe0dbf57cddf5946d1586", features = ["stdlib"] }
half = "2"
serde = { version = "1.0", features = ["std", "derive"] }
hound = "3.5.1"
tokenizers = { version = "0.22.2", default-features = false, features = ["onig"] }
strum = "0.28.0"
strum_macros = "0.28.0"
log = "0.4"
mt19937 = "3.3.0"