[package]
name = "fast-whisper-burn"
version = "0.1.0"
edition = "2024"

[dependencies]
#burn         = { version = "0.22.0-pre.1", features = ["autotune", "fusion", "flex", "extension"] }
#burn-store   = { version = "0.22.0-pre.1", features = ["burnpack", "pytorch"] }
#burn-cubecl  = { version = "0.22.0-pre.1" }
#burn-fusion  = { version = "0.22.0-pre.1" }
#burn-ir      = { version = "0.22.0-pre.1" }
#burn-backend = { version = "0.22.0-pre.1" }
#cubecl       = { version = "0.11.0-pre.1", features = ["stdlib"] }
burn         = { git = "https://github.com/tracel-ai/burn", rev = "b6e27bd", default-features = false, features = ["std", "autotune", "fusion", "flex", "extension"] }
burn-store   = { git = "https://github.com/tracel-ai/burn", rev = "b6e27bd", features = ["burnpack", "pytorch"] }
burn-cubecl  = { git = "https://github.com/tracel-ai/burn", rev = "b6e27bd" }
burn-fusion  = { git = "https://github.com/tracel-ai/burn", rev = "b6e27bd" }
burn-ir      = { git = "https://github.com/tracel-ai/burn", rev = "b6e27bd" }
burn-backend = { git = "https://github.com/tracel-ai/burn", rev = "b6e27bd" }
cubecl       = { git = "https://github.com/tracel-ai/cubecl", rev = "088dd7053c039775f73cf4d1645d30706d0ddf7d", features = ["stdlib"] }
half = "2"
serde = { version = "1.0", features = ["std", "derive"] }
hound = "3.5.1"
tokenizers = { version = "0.23.1", default-features = false, features = ["onig"] }
strum = "0.28.0"
strum_macros = "0.28.0"
log = "0.4"
mt19937 = "3.3.0"
simplelog = "0.12"

[features]
default = ["wgpu"]
wgpu   = ["burn/wgpu"]
metal  = ["burn/metal"]
vulkan = ["burn/vulkan"]
webgpu = ["burn/webgpu"]
cuda   = ["burn/cuda"]